services:
  host-agent:
    build: .
    container_name: satis-host-agent
    hostname: host-agent
    ports:
      - "${HOST_AGENT_PORT:-8082}:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Docker-in-Docker access
      - ./data:/data  # Shared data directory for servers
      - ./rathole-configs:/rathole-configs  # Rathole client configs
    environment:
      - ORCHESTRATOR_HOST=${ORCHESTRATOR_HOST}
      - ORCHESTRATOR_PORT=${ORCHESTRATOR_PORT}
      - RATHOLE_INSTANCE_MANAGER_HOST=${RATHOLE_INSTANCE_MANAGER_HOST}
      - RATHOLE_INSTANCE_MANAGER_PORT=${RATHOLE_INSTANCE_MANAGER_PORT}
      - RATHOLE_TOKEN=${RATHOLE_TOKEN}
      - HOST_AGENT_API_KEY=${HOST_AGENT_API_KEY}
      - NODE_ID=${NODE_ID}
      # Disable Flask debug mode to prevent double startup
      - FLASK_DEBUG=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - orchestrator_satisfactory-network
    restart: unless-stopped

networks:
  orchestrator_satisfactory-network:
    external: true
