services:
  frp-instance-manager:
    build:
      context: .
      dockerfile: Dockerfile.instance-manager
    container_name: frp-instance-manager
    restart: unless-stopped
    ports:
      - "7000:7000/tcp"       # frps control port
      - "7000:7000/udp"
      - "7500:7500"          # frps dashboard
      - "7001:7001"           # Instance Manager API (HTTP)
      - "40000-40100:40000-40100/tcp"  # Port range for tunneled game traffic
      - "40000-40100:40000-40100/udp"  # Port range for tunneled game traffic (UDP)
    environment:
      # === REQUIRED: Update these values ===
      - PUBLIC_HOST_IP=69.164.196.13  #  Actual host/LAN IP
      - PUBLIC_IP=${PUBLIC_IP:-0.0.0.0}  # For server binding (optional, defaults to 0.0.0.0)
      - INTERNAL_SERVER_HOST=69.164.196.13
      - FRP_SERVER_HOST=69.164.196.13
      - API_TOKEN=ZulFyyu3FraFfIuDxQe73pJJPXxuyOOrk2tqQKL7HwM3XGDKTQp7oH4v6gcgP86Kir79uicVJIZtj79dy4Q1svSrSxT2UDWGcejb2am3p1j7Wl2Rj5jKhuErIdi2jYB
      # === Security Configuration ===
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL:-http://auth-service:8081}
      - USE_HTTPS=${USE_HTTPS:-false}
      - SSL_CERT_PATH=/certs/server.crt
      - SSL_KEY_PATH=/certs/server.key
      
      # === Legacy Auth (DISABLED) ===
      - LEGACY_AUTH_ENABLED=false
      
      # === Instance Manager Configuration ===
      - SERVER_PORT=7001
      - HTTPS_PORT=443
      - FRP_BINARY=/usr/local/bin/frps
      - BASE_DATA_DIR=/data/frp-instances
      
      # === Port Allocation Ranges ===
      - GAME_PORT_START=40000
      - GAME_PORT_END=40100
      
      # === Flask Settings ===
      - FLASK_ENV=production
    volumes:
      - frp_instances_data:/data/frp-instances
      - frp_logs:/var/log/frp
      - ./certs:/certs:ro        # SSL certificates (optional, create directory if using HTTPS)
    networks:
      - frp_network
      - auth-service_auth-network  # Connect to the auth service network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  frp_instances_data:
    driver: local
  frp_logs:
    driver: local
networks:
  frp_network:
    driver: bridge
  auth-service_auth-network:
    external: true  # Use the existing auth service network
